version: '3.6'

services:
  rvm:
    build:
      context: .
      args:
        - RVM_PASS=${RVM_PASS}
    volumes:
      - '.:/usr/src/app'
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true
